name: purecode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  window_manager: ^0.3.7 # Agrega esta línea para incluir la dependencia window_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/backend/ # Incluye esta línea para que Flutter reconozca la carpeta backend y su contenido el (main.exe), aunque esté vacía.
    #- assets/backend/_internal/ # Incluye esta línea para que Flutter reconozca la carpeta _internal y su contenido (main.exe), aunque esté vacía.
    - assets/cleanpc/mac.png
    - assets/cleanpc/win.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256

# Nota para el futuro: 
# Para generar los iconos, asegúrate de estar en Source/client y corre:
# dart run flutter_launcher_icons
# flutter pub get